/** Metadata written when an agent's passage storage is initialized. */
export interface AgentManifest {
  agentId: string;
  name: string;
  model: string;
  tags: string[];
  createdAt: string;
}

/** A stored passage: opaque ID + full text. */
export interface StoredPassage {
  id: string;
  text: string;
}

/** A semantic-search hit over an agent's passages. */
export interface PassageSearchResult {
  id: string;
  text: string;
  /** Fused relevance score (higher is better); not cosine similarity. */
  score: number;
}

/**
 * Narrow storage/retrieval surface the agent provider needs for passages.
 * Implementations own persistence and semantic search; passage IDs are
 * generated by the caller so state bookkeeping stays provider-agnostic.
 */
export interface PassageStore {
  initAgent(this: void, agentId: string, manifest: AgentManifest): Promise<void>;
  deleteAgent(this: void, agentId: string): Promise<void>;
  listAgents(this: void): Promise<string[]>;
  writePassage(this: void, agentId: string, passageId: string, text: string): Promise<void>;
  readPassage(this: void, agentId: string, passageId: string): Promise<string>;
  deletePassage(this: void, agentId: string, passageId: string): Promise<void>;
  listPassages(this: void, agentId: string): Promise<StoredPassage[]>;
  semanticSearch(this: void, agentId: string, query: string, limit: number): Promise<PassageSearchResult[]>;
}
